### ISSUE TITLE
Support LTR/RTL-only declarations

### ISSUE THREAD

**Issue by necolas** [twitter-archive/css-flip#1]
For example, flipping sprites or setting different generated content for icon fonts.

``` css
.a {
  /* @onlyrtl */ background-position: 0 -30px;
  /* @onlyltr */ background-position: 0 -100px;
}
```

**Comment by necolas** [comment]
Might need to adjust the API to something like `cssflip(css, 'rtl')`, where the second param indicates the output direction (which we can use to assume the input is the opposite).

**Comment by mathiasbynens** [comment]
Might be more future-proof to use an object for the second parameter, i.e. `cssflip(css, { output: 'rtl' })` — in case you want/need to add more options later.

**Comment by brettstimmerman** [comment]
+1 @mathiasbynens 

@necolas: An `/*@ltronly*/` directive will work well. Since cssflip currently works under the assumption that `output='rtl'`, any `@ltronly` directives can be handled during the flip.

But satisfying an `/*@rtlonly*/` directive for LTR output would require passing CSS a second time through `cssflip(css, {output: 'ltr'})` for the sole purpose of removing opposite-directioned rules/declarations, but zero directional flipping.

Thinking out loud: Perhaps a second "global noflip" option could solve this: `{noflip: true}`. When this flag is set, cssflip would process output direction directives only -- no flipping would occur.

Putting both options together with your example CSS above, processing both directives would require two passes through cssflip:

``` js
var ltr_css = cssflip(css, {output: 'ltr', noflip: true});
var rtl_css = cssflip(css, {output: 'rtl'}); // or simply `cssflip(css)`
```

LTR output:

``` css
.a {
  /* @onlyltr */ background-position: 0 -100px;
}
```

RTL output:

``` css
.a {
  /* @onlyrtl */ background-position: 0 -30px;
}
```

**Comment by mathiasbynens** [comment]
`noflip: true` or `flip: false`?

**Comment by ljharb** [comment]
Absence of an optional value should always equate to false - `flip: false` works as long as not providing `flip` also means false.

**Comment by necolas** [comment]
i also think `input: 'ltr'` might be nicer than `output`. because the output should always 'flip' the explicitly known input direction…unless you `noflip: true`. a bit more intuitive imo.

**Comment by brettstimmerman** [comment]
Any thoughts on requiring two passes to cover input and output direction directives?

**Comment by ds125v** [comment]
Seems a shame to make people declare their direction when it currently works either way.
Would 'flip-add/flip-remove/flip-replace' work? And I'm not sure of the technical issues, but having the rules intended only for the flipped version in a comment when not flipped would suit me, as it would get stripped out anyway by another process.

**Comment by necolas** [comment]
Or how about something like this:

``` css
.a {
  /* @flip: 0 -30px */ background-position: 0 -100px;
}
```

You specify the flipped value in a comment. Means that it works by default (no extra pass required), and no change to the JS API is needed.
